### ISSUE TITLE
Delete me

### ISSUE THREAD

**Issue by SocksAndStuff** [GTekSD/BurpSuitePro-1.7.37-and-2022.8.5-Cracked#2]
java --illegal-access=permit -Dfile.encoding=utf-8 -javaagent:"C:\Users\Admin\AppData\Local\Programs\BurpSuitePro\loader.jar" 

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0

I must be doing something wrong right?

**Comment by SocksAndStuff** [comment]
solved the issue, feel free to delete this

**Comment by GTekSD** [comment]
sweet!
